CREATE TABLE IF NOT EXISTS bobyn_users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  avatar_emoji VARCHAR(10) DEFAULT '🦉',
  created_at TIMESTAMP DEFAULT NOW()
);