ALTER TABLE bobyn_users ADD COLUMN IF NOT EXISTS bobyz VARCHAR(32) UNIQUE;
ALTER TABLE bobyn_users ADD COLUMN IF NOT EXISTS theme VARCHAR(20) DEFAULT 'dark';
ALTER TABLE bobyn_users ADD COLUMN IF NOT EXISTS locale VARCHAR(10) DEFAULT 'ru';